#define BUILD_COMMIT_ID "f3c4948"
#define PROJECT_VERSION "5.0.0"
#define PROJECT_VERSION_BUILD_NO "f3c4948"
#define PROJECT_VERSION_LONG PROJECT_VERSION
#define VERSION_MAJOR "5"
#define VERSION_MINOR "0.0"
#define VERSION_PATCH ""
#define GIT_REVISION "f3c4948-Release"
